# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1beta5'
kind: 'Template'

desc:
  'A template that sets up a protos directory along with a script to generate language specific protos.'

inputs:
  - name: 'github_org_name'
    desc: 'The name of the github org the repo will belong to'
  - name: 'github_repo_name'
    desc: 'The name of the github repo'
  - name: 'protobuf_version'
    desc: 'The protobuf version to use, see https://github.com/protocolbuffers/protobuf/releases'
    default: '24.3'
  - name: 'protoc_gen_go_version'
    desc: 'The protoc go plugin version to use, see https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go'
    default: '1.31.0'
  - name: 'go_version'
    desc: 'The go version to use'
    default: '1.21.1'
  - name: 'go_gar_proto_version'
    desc: 'prefix for the uploaded go GAR artifact'
    default: 'v0.0.0'
  - name: 'wif_provider'
    desc: 'The WIF provider that has access to the GAR repositories'
  - name: 'wif_service_account'
    desc: 'The service account associated to the WIF provider'
  - name: 'project_id'
    desc: 'The project ID where the GARs are hosted'
  - name: 'go_gar_repository_name'
    desc: 'Name of the go GAR'
  - name: 'go_gar_repository_location'
    desc: 'Region of the go GAR'
  - name: 'go_module_path'
    desc: 'Module path of the go protos module'

steps:
  - desc: 'Include some files and directories'
    action: 'include'
    params:
      paths: ['protos', 'scripts', '.github', 'prototool.yaml']
  - desc: 'Replace proto related configurations'
    action: 'string_replace'
    params:
      paths: ['.']
      replacements:
        - to_replace: 'REPLACE_GITHUB_ORG_NAME'
          with: '{{.github_org_name}}'
        - to_replace: 'REPLACE_GITHUB_REPO_NAME'
          with: '{{.github_repo_name}}'
        - to_replace: 'REPLACE_PROTOBUF_VERSION'
          with: '{{.protobuf_version}}'
        - to_replace: 'REPLACE_PROTOC_GEN_GO_VERSION'
          with: '{{.protoc_gen_go_version}}'
        - to_replace: 'REPLACE_GO_VERSION'
          with: '{{.go_version}}'
        - to_replace: 'REPLACE_WIF_PROVIDER'
          with: '{{.wif_provider}}'
        - to_replace: 'REPLACE_WIF_SERVICE_ACCOUNT'
          with: '{{.wif_service_account}}'
        - to_replace: 'REPLACE_PROJECT_ID'
          with: '{{.project_id}}'
        - to_replace: 'REPLACE_GO_GAR_REPOSITORY_NAME'
          with: '{{.go_gar_repository_name}}'
        - to_replace: 'REPLACE_GO_GAR_REPOSITORY_LOCATION'
          with: '{{.go_gar_repository_location}}'
        - to_replace: 'REPLACE_GO_MODULE_PATH'
          with: '{{.go_module_path}}'
        - to_replace: 'REPLACE_GO_GAR_PROTO_VERSION'
          with: '{{.go_gar_proto_version}}'
