# Copyright 2024 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1beta3'
kind: 'Template'

desc: 'An example of using builtin git variables in a template'

steps:
  - desc: 'Print a message if being rendered from git'
    action: 'print'
    if: '_git_sha != ""'
    params:
      message: 'This template is rendered from git. The git short SHA is
        {{._git_short_sha}} and the full SHA is {{._git_sha}}.'
  - desc: 'Print the git tag if there is one'
    action: 'print'
    if: '_git_tag != ""'
    params:
      message: 'And furthermore, the git tag associated with that SHA is {{._git_tag}}.'
  - desc: "If we're rendering from git and there's no tag, then say that"
    action: 'print'
    if: '_git_sha != "" && _git_tag == ""'
    params:
      message: 'There is not a tag pointing to this SHA.'
  - desc: 'Print a message if NOT being rendered from git'
    action: 'print'
    if: '_git_sha == ""'
    params:
      message: 'This template is not being rendered from git, so there is no SHA or tag.'