import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Auth from './auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'React Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <Auth />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
