# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1alpha1'
kind: 'Template'
desc: 'REST server workflows template'
inputs:
  - name: 'automation_service_account'
    desc: 'Automation Service Account (ex: [account_name]@[project_id].iam.gserviceaccount.com)'
  - name: 'wif_provider'
    desc: 'Workload Identity Federation Provider (ex: projects/[project_id]/locations/global/workloadIdentityPools/[WIF_pool_name]/providers/[provider_name])'
  - name: 'ar_repository'
    desc: 'Artifact Registry Repository (ex: ci-images)'
  - name: 'ar_location'
    desc: 'Artifact Registry Location (ex: us-docker.pkg.dev)'
  - name: 'cr_service'
    desc: 'Cloud Run Service (ex: hello-jupiter-api)'
  - name: 'region'
    desc: 'Cloud Run Region (ex: us-west1)'
  - name: 'project_id'
    desc: 'GCP Project ID'
steps:
  - desc: 'Include config'
    action: 'include'
    params:
      paths: ['contents/config']
      as: ['.github/config']
  - desc: 'Include Dockerfile'
    action: 'include'
    params:
      paths: ['contents/Dockerfile']
      as: ['Dockerfile']
  - desc: 'Include CI workflow'
    action: 'include'
    params:
      paths: ['contents/ci-rest-server.yaml']
      as: ['.github/workflows/ci-rest-server.yaml']
  - desc: 'Include deployment workflow'
    action: 'include'
    params:
      paths: ['contents/deploy-rest-server.yaml']
      as: ['.github/workflows/deploy-rest-server.yaml']
  - desc: 'Replace sentinel values with real input values'
    action: 'string_replace'
    params:
      paths: ['.']
      replacements:
        - to_replace: 'AUTOMATION_SERVICE_ACCOUNT=[automation_service_account]'
          with: 'AUTOMATION_SERVICE_ACCOUNT={{.automation_service_account}}'
        - to_replace: 'WIF_PROVIDER=[wif_provider]'
          with: 'WIF_PROVIDER={{.wif_provider}}'
        - to_replace: 'AR_REPOSITORY=[ar_repository]'
          with: 'AR_REPOSITORY={{.ar_repository}}'
        - to_replace: 'AR_LOCATION=[ar_location]'
          with: 'AR_LOCATION={{.ar_location}}'
        - to_replace: 'CR_SERVICE=[cr_service]'
          with: 'CR_SERVICE={{.cr_service}}'
        - to_replace: 'REGION=[region]'
          with: 'REGION={{.region}}'
        - to_replace: 'PROJECT_ID=[project_id]'
          with: 'PROJECT_ID={{.project_id}}'
