# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1alpha1'
kind: 'Template'
desc: 'A React template built by NextJS.'
inputs:
  - name: 'session_secret'
    desc: 'A long secret value used to encrypt the session cookie `openssl rand -hex 32`'
  - name: 'base_url'
    desc: 'The base URL of the application'
    default: 'http://localhost:3000'
  - name: 'issuer_base_url'
    desc: 'The base URL of the Auth0 tenant domain'
  - name: 'client_id'
    desc: 'The application Auth0 Client ID'
  - name: 'client_secret'
    desc: 'The application Auth0 Client Secret'
steps:
  - desc: 'Include some files and directories'
    action: 'include'
    params:
      paths:
        - 'contents'
        - '.auth0config'
      as:
        - '.'
        - '.env.local'
  - desc: 'Replace Auth0 configuration variables'
    action: 'string_replace'
    params:
      paths: ['.env.local']
      replacements:
        - to_replace: 'REPLACE_AUTH0_SECRET'
          with: '{{.session_secret}}'
        - to_replace: 'REPLACE_AUTH0_BASE_URL'
          with: '{{.base_url}}'
        - to_replace: 'REPLACE_AUTH0_ISSUER_BASE_URL'
          with: '{{.issuer_base_url}}'
        - to_replace: 'REPLACE_AUTH0_CLIENT_ID'
          with: '{{.client_id}}'
        - to_replace: 'REPLACE_AUTH0_CLIENT_SECRET'
          with: '{{.client_secret}}'
