import './global.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {UserProvider} from '@auth0/nextjs-auth0/client';
import NavBar from './navbar';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'React Template',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <head>
        <meta
          http-equiv="Content-Security-Policy"
          content="require-trusted-types-for 'script'"
        />
      </head>
      <UserProvider>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
