name: 'ci'

on:
  workflow_call:
    outputs:
      proto_version:
        description: 'The proposed proto version'
        value: '${{ jobs.version.outputs.proposed_proto_version }}'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

concurrency:
  group: 'ci-${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GO_VERSION: 'REPLACE_GO_VERSION'
  BUF_VERSION: 'REPLACE_BUF_VERSION'
  BUF_CHECKSUM: 'REPLACE_BUF_CHECKSUM'

jobs:
  version:
    runs-on: 'ubuntu-latest'
    outputs:
      proposed_proto_version: '${{ steps.capture.outputs.PROPOSED_PROTO_VERSION }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
      - name: 'Capture proposed version'
        id: 'capture'
        run: |
          echo "PROPOSED_PROTO_VERSION=$(yq eval '.proto_version' version.yaml)" >> $GITHUB_OUTPUT

  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@cfc3ba96621bb047468244993c7fb8cdd63b3352' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
          install_path: '${{ runner.temp }}/.buf'
          binary_subpath: 'buf/bin/buf'
          checksum: '${{ env.BUF_CHECKSUM }}'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
          add_to_path: true

      - name: 'Run Build'
        shell: 'bash'
        run: |
          set +e
          BUILD_CHECK=$(buf build)
          if ! [[ -z "${BUILD_CHECK}" ]]; then
            echo "::error::$BUILD_CHECK"
            exit 1
          fi

  lint:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@cfc3ba96621bb047468244993c7fb8cdd63b3352' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
          install_path: '${{ runner.temp }}/.buf'
          binary_subpath: 'buf/bin/buf'
          checksum: '${{ env.BUF_CHECKSUM }}'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
          add_to_path: true

      - name: 'Run Lint'
        shell: 'bash'
        run: |
          set +e
          LINT_CHECK=$(buf lint)
          if ! [[ -z "${LINT_CHECK}" ]]; then
            echo "::error::$LINT_CHECK"
            exit 1
          fi

  regenerate:
    runs-on: 'ubuntu-latest'
    needs:
      - 'build'
      - 'version'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Go'
        uses: 'actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491' # ratchet:actions/setup-go@v5
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: 'Setup Buf CLI'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@cfc3ba96621bb047468244993c7fb8cdd63b3352' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
          install_path: '${{ runner.temp }}/.buf'
          binary_subpath: 'buf/bin/buf'
          checksum: '${{ env.BUF_CHECKSUM }}'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
          add_to_path: true

      - name: 'Run Generate'
        env:
          PROTO_VERSION: '${{ needs.version.outputs.proposed_proto_version }}'
        shell: 'bash'
        run: |
          set +e
          make generate
          DIFF=$(git status --porcelain)
          echo $DIFF
          if ! [[ -z "${DIFF}" ]]; then
            echo "::error::Files were not generated from latest proto changes, run make generate and push the latest changes."
            exit 1
          fi

  breaking:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Checkout PR branch'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}'

      - name: 'Setup Buf CLI'
        uses: 'abcxyz/pkg/.github/actions/setup-binary@cfc3ba96621bb047468244993c7fb8cdd63b3352' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
        with:
          download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
          install_path: '${{ runner.temp }}/.buf'
          binary_subpath: 'buf/bin/buf'
          checksum: '${{ env.BUF_CHECKSUM }}'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
          add_to_path: true

      - name: 'Run Break Check'
        shell: 'bash'
        run: |
          set +e
          BREAK_CHECK=$(buf lint --against https://github.com/REPLACE_GITHUB_ORG_NAME/REPLACE_GITHUB_REPO_NAME.git#branch=main,ref=HEAD~1)
          if ! [[ -z "${BREAK_CHECK}" ]]; then
            echo "::error::$BREAK_CHECK"
            exit 1
          fi
