name: 'notify-on-issue-and-release'

on:
  issues:
    types: [opened]
  release:
    types: [released]
  workflow_dispatch:
     

jobs:
  call_action:
    runs-on: 'ubuntu-latest'
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3' # ratchet:actions/checkout@v3
      - name: 'call action'
        uses: 'google-github-actions/send-google-chat-webhook@v0.0.2'
        with:
          webhook_url: '${{ secrets.WEBHOOK_URL }}'
